### PR TITLE
Bump ember-cli-blueprint-test-helpers to v0.10.0 and enabled skipped test

### PR DESCRIPTION
**Pull request by trabus**
:facepunch:

### CODE REVIEW

**Comment by trabus** [comment]
After this is merged, I think we should cut a new version for https://github.com/ember-cli/ember-cli/pull/5648

**Comment by trabus** [comment]
@Turbo87 @stefanpenner r+ ?

**Comment by Turbo87** [comment]
@homu r+

**Comment by trabus** [comment]
@Turbo87 Thanks!

If there's no objections, I'm going to cut a new version for the ember-cli PR.

**Comment by rwjblue** [comment]
:shipit:

**Comment by trabus** [comment]
Looking at the package.json, I think we need to cleanup a bit. We shouldn't be depending on ember-data for development. https://github.com/ember-cli/ember-cli-legacy-blueprints/blob/master/package.json#L36

**Comment by trabus** [comment]
Also removing `bower.json` and `.bowerrc`

**Pull request merged**
