### PR TITLE
Fix Windows line ending issues

### LINKED ISSUE #5: appveyor tests
- [x] enable appveyor (on its side)
- [x] add appveyor.yml -> https://github.com/ember-cli/ember-cli-legacy-blueprints/pull/6
- [x] add to readme
- [ ] make green

### PR DESCRIPTION
**Pull request by Turbo87**
resolves #5

### CODE REVIEW

**Comment by rwjblue** [comment]
LGTM, should we have @kellyseldon or other Windows running contrib to test?

**Comment by Turbo87** [comment]
sure couldn't hurt if someone on Windows would verify, although I'm pretty confident about these changes as they're basically just copied from `ember-cli`

**Comment by Turbo87** [comment]
@rwjblue AppVeyor is green :shipit:

**Comment by rwjblue** [comment]
@homi r+

**Comment by rwjblue** [comment]
@homu r+

**Comment by rwjblue** [comment]
Grrrr

**Comment by stefanpenner** [comment]
:+1:

**Comment by kellyselden** [comment]
:+1: better late than never!

**Pull request merged**
