### PR TITLE
Use Babel transpilation for node-tests

### PR DESCRIPTION
**Pull request by Turbo87**
This PR uses Babel to transpile the test code from ES2015 to something that even Node 0.10 can handle. Note that this is only used for the test code, **not for the production code** (`.babelrc` is in `node-tests` subfolder)!

### CODE REVIEW

**Comment by rwjblue** [comment]
Seems good to me. 

@stefanpenner - r?

**Comment by stefanpenner** [comment]
Abit strange to mix Babel 5 and 6 no?

**Comment by Turbo87** [comment]
@stefanpenner true, but then again I don't see a reason for using on an outdated Babel version if we can use the new one without pain here

**Comment by nathanhammond** [comment]
I'm generally opposed to introducing Babel in `node` land for reasons of debugging and source maps. If those work nicely then I don't care nearly as much. I would want to limit it to things that aren't part of typical package usage, like tests (which you're already doing).

My opinion is informed by the relative ease with which we can update `node` to move the ecosystem to things which are already implemented in V8.

**Comment by Turbo87** [comment]
@nathanhammond I've limited the installed/enabled babel plugins to just `transform-es2015-arrow-functions` and `transform-es2015-shorthand-properties` now. From what I've experienced so far that isn't screwing up the stacktraces in any noticable way.

**Comment by nathanhammond** [comment]
@Turbo87 With that limitation I'm in favor.

**Comment by Turbo87** [comment]
@stefanpenner @trabus r?

**Pull request merged**
