### PR TITLE
Fixes leading slash being added to component-test module name

### PR DESCRIPTION
**Pull request by lpaluszk**
@Turbo87 As requested in https://github.com/ember-cli/ember-cli/pull/5673. Cheers

### CODE REVIEW

**Comment by Turbo87** [comment]
That's fast delivery, awesome! Could you maybe add a test case for that as well?

**Comment by lpaluszk** [comment]
Yes! Definitely. I was looking for tests in the original ember-cli project but I couldn't find any blueprint tests.

**Comment by Turbo87** [comment]
They exist but they are much more hidden than here. Don't worry too much about the ember-cli repo though because we're about to remove the majority of the templates there soon. This repo here and ember.js will take over instead.

**Comment by lpaluszk** [comment]
@Turbo87 Is this any good? I ran the tests and it fails as expected before the change in the other commit. Passes fine afterwards.

I've just written my first test. Yay!

**Comment by Turbo87** [comment]
Yeah, that looks exactly how it should be! 

@homu r+

**Pull request merged**
