### PR TITLE
Stop including the name in initializer blueprints.

### PR DESCRIPTION
**Pull request by eventualbuddha**
The module name serves as the name.

### CODE REVIEW

**Comment by eventualbuddha** [comment]
The build is actually okay, but the [node v0.12 version timed out for some reason](https://travis-ci.org/ember-cli/ember-cli-legacy-blueprints/jobs/161179860).

**Comment by Turbo87** [comment]
is there a corresponding PR in the ember.js repo?

**Comment by eventualbuddha** [comment]
@Turbo87 there is now: https://github.com/emberjs/ember.js/pull/14338

**Comment by Turbo87** [comment]
@eventualbuddha cool, thanks! our policy is usually to get it merged into the `ember.js` or `ember-data` repos first and then adopt it here.

**Comment by locks** [comment]
*NOTE* ONLY MERGE WHEN https://github.com/emberjs/ember.js/pull/14338 IS IN A RELEASE

**Comment by Turbo87** [comment]
@locks why?

**Pull request merged**
